import { StyleSheet } from "react-native";
const stylem = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f3f0ec',
    position: 'relative',
      width: '100%',
      height: '100%',
  },
  
  title1: {
    position:'absolute',
    fontStyle: 'normal',
    fontWeight: '600',
    textAlign:'left',
    fontSize: 20,
    lineHeight: 58,
    color: '#5C514D',
    marginTop: '12%',
    marginRight:'3%',
    marginLeft: '5%',
  },
  box1:{
    width: 280,
    height: 130,
    left: 12, right:20,
    position:'absolute',
    backgroundColor:'#faf9f6',
    borderRadius: 5,
    marginTop: '30%',marginLeft:'2%'
  },
  title2: {
    position:'absolute',
    fontStyle: 'normal',
    fontWeight: '600',
    textAlign:'right',
    fontSize: 20,
    lineHeight: 28,
    color: '#5C514D',
    marginTop: '8%',
    marginRight:'1%',
    marginLeft: '25%',
  },
  button: {
    position:'absolute',
    marginTop: '22%',
    marginLeft: '26%',
    width: '75%',
  },
  box2:{
    width: 280,
    height: 30,
    left: 20, right:25,
    position:'absolute',
    backgroundColor:'#dbcfc5',
    borderRadius: 10,
    marginTop: '79%',
  },
  title3: {
    position:'absolute',
    fontStyle: 'normal',
    fontWeight: '600',
    textAlign:'right',
    fontSize: 16,
    lineHeight: 15,
    color: '#5C514D',
    marginTop: '8%',
    marginRight:'1%',
    marginLeft: '5%',
  },
  stat: {

  },
  box3:{
    width: 130,
    height: 28,
    left: 2, right:25,
    position:'absolute',
    backgroundColor:'#ffffff',
    borderRadius: 5,
    marginTop: '27%',
  },
  box4:{
    width: 130,
    height: 65,
    left: 2, right:15,
    position:'absolute',
    backgroundColor:'#ffffff',
    borderRadius: 5,
    marginTop: '27%',
    marginLeft: '50%',
  },
  text: {
    position:'absolute',
    fontStyle: 'normal',
    fontWeight: '600',
    textAlign:'right',
    fontSize: 18,
    lineHeight: 28,
    color: '#5C514D',
    marginTop: '2%',
    marginLeft: '20%',
  },
  box5:{
    width: 280,
    height: 200,
    left: 2, right:18,
    position:'absolute',
    marginTop: '55%',
  },
  image2: {
    position:'absolute',
    width: '60%',
    height: 170,
    marginTop:'10%',marginLeft: '15%'
  },
  title4: {
    position:'absolute',
    fontStyle: 'normal',
    fontWeight: '600',
    textAlign:'right',
    fontSize: 19,
    lineHeight: 28,
    color: '#5C514D',
  },
  btn: {
    position: 'relative',
    marginLeft:'70%',
    marginTop: '65%'
  }
});
export default stylem;